image:
  - Visual Studio 2019

# Build only on the master branch, for PRs
branches:
  only:
    - master

# Skip any commit that doesn't have [MSVC] in the commit message.
only_commits:
  message: /\[MSVC\]/

build:
  parallel: true
  verbosity: detailed

configuration:
  - Debug
  - Release

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    - platform: x64

cache:
  - C:\Tools\vcpkg\installed

init:
  - echo Appveyor Image = %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set "generator=Visual Studio 16 2019" && set "toolset=v142" )
  - echo Generator = %generator%

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %appveyor_build_folder%
  - vcpkg install boost-asio:%platform%-windows
  - vcpkg install boost-range:%platform%-windows
  - vcpkg install gsl-lite:%platform%-windows

build_script:
  - mkdir build
  - cd build
  - cmake -G "%generator%" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake  ..
  - cmake --build . --config %configuration%
