language: cpp
os: linux

compiler:
  - clang

linux_gcc: &linux_gcc
  os: linux
  dist: xenial
  compiler: gcc
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:mhier/libboost-latest'
      packages:
        - g++-5
        - boost1.74

linux_clang: &linux_clang
  os: linux
  dist: xenial
  compiler: clang
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:mhier/libboost-latest'
      packages:
        - clang-4.0
        - boost1.74

jobs:
  include:
    - <<: *linux_gcc
    - <<: *linux_clang
    - <<: *linux_gcc
      addons:
        apt:
          packages:
            python3-pip
      env: USE_CONAN=true
        

cache:
  directories:
    - $HOME/3party
    - $HOME/.conan

before_install:
  - export EXTERNAL_ROOT=$HOME/3party
  - if [ "$USE_CONAN" == "true" ]; then
      ./.travis/fetch_conan_dependencies.sh;
    else
      ./.travis/fetch_system_dependencies.sh;
    fi

before_script:
  - mkdir build || true
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$EXTERNAL_ROOT ..

script:
  - make VERBOSE=1

notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
  slack:
    rooms:
      - kazdragon:${SLACK_TOKEN}#ci
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/${GITTER_TOKEN}
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
