name: CMake

on:
  pull_request:
  push:
    branches: master

env:
  EXTERNAL_ROOT: /home/runner/3party

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_type: Debug
          - build_type: Release

    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add Boost repository
        shell: bash
        run: sudo apt-add-repository ppa:mhier/libboost-latest

      - name: Install latest Boost
        shell: bash
        run: sudo apt install libboost1.74-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/serverpp/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/serverpp/build
        run: cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=$EXTERNAL_ROOT

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/serverpp/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/serverpp/build
        shell: bash
        run: ctest -C $BUILD_TYPE
